name: Run test suite on docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Use the official Playwright image which includes Python and Browsers
    container:
      image: mcr.microsoft.com/playwright/python:v1.58.0-jammy 

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright pytest-xdist pytest-html allure-pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install-deps

    - name: Lint with flake8
    # MEMO: 
    # that specific flake8 command is designed to be a "Smoke Test" for the code syntax. 
    # The flags --select=E9,F63,F7,F82 tell Flake8 to look only for "catastrophic" errors, 
    # such as:
    # E9: Syntax errors (e.g., a missing parenthesis).
    # F63: Logic issues (e.g., using is with a constant).
    # F7: Break/Continue statements outside of loops.
    # F82: Undefined names (e.g., calling a variable you never created).
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Playwright tests
      # I am not running 'playwright install' because they are in the image
      # run the tests in parallel
      run: pytest -n auto --browser chromium --browser firefox

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          reports/
          results_Playwright/
          allure-results/
          retention-days: 30
        
